## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

#### 교과목명 : Python 분석라이브러리 활용

- 평가일 : 21.7.26
- 성명 : 조경림
- 점수 : 89

### Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열을 아래와 같이 생성하세요.
1차원  
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]  

2차원  
[[ 1  2  3  4  5]  
  [ 6  7  8  9 10]  
  [11 12 13 14 15]  
  [16 17 18 19 20]] 

3차원  
[[[ 1  2  3  4  5]  
  [ 6  7  8  9 10]]  
 
 [[11 12 13 14 15]  
  [16 17 18 19 20]]]

In [17]:
import numpy as np
import pandas as pd

ar = np.arange(1,21).reshape(20)
print(ar,'\n')

ar2 = ar.reshape(4,5)
print(ar2,'\n')

ar3 = ar.reshape(2,2,5)
print(ar3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


### Q2. 1 ~ 100 까지 배열에서 3과 7의 공배수중에서 42의 배수인 것만을 출력하세요.

In [244]:
arr = np.arange(1,101)
print(arr)

print(arr[(arr%3==0)&(arr%7==0)&(arr%42==0)])

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[42 84]


### Q3. 아래 3차원 배열을 생성하여 출력한 후 1차원으로 변환하여 출력하세요.(reshape() 사용)

[[[ 0  1  2  3]  
  [ 4  5  6  7]  
  [ 8  9 10 11]]  
  
 [[12 13 14 15]  
  [16 17 18 19]  
  [20 21 22 23]]]

In [34]:
arr3 = np.arange(0,24).reshape(2,3,4)
print(arr3,'\n')

arr1 = arr3.reshape(24)
print(arr1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Q4. array2d에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
arr2d = np.arange(11,20).reshape(3,3)

[13 16]  

[[11 12]  
 [14 15]]

[[11 12 13]  
 [14 15 16]]

In [50]:
arr2d = np.arange(11,20).reshape(3,3)
print(arr2d,'\n')

print(arr2d[(0,1),2], '\n')
print(arr2d[0:2,0:2],'\n')
print(arr2d[0:2])

[[11 12 13]
 [14 15 16]
 [17 18 19]] 

[13 16] 

[[11 12]
 [14 15]] 

[[11 12 13]
 [14 15 16]]


### Q5. 아래 두행렬을 np.arange, reshape를 이용해서 생성 각각 a1, b1으로 저장하고 행렬 내적을 계산한 결과를 출력하세요.

[[ 1  2  3  4  5]  
 [ 6  7  8  9 10]  
 [11 12 13 14 15]]

[[10 11 12 13]  
 [14 15 16 17]  
 [18 19 20 21]  
 [22 23 24 25]  
 [26 27 28 29]]

In [53]:
a1 = np.arange(15).reshape(3,5) 
b1 = np.arange(10,30).reshape(5,4)
print(a1, '\n')
print(b1, '\n')

print(a1.dot(b1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]] 

[[ 220  230  240  250]
 [ 670  705  740  775]
 [1120 1180 1240 1300]]


### Q6. ar의 역행렬을 출력하고 검증을 수행하세요.
지수표현식을 실수 표현으로 변경 : np.set_printoptions(precision=6, suppress=True)

In [247]:
np.random.seed(1)
ar = np.random.randint(1,6,size=(5,5))
ar_a = np.linalg.inv(ar)

np.set_printoptions(precision=6, suppress=True)

print('행렬:', '\n', ar)
print('역행렬:','\n', ar_a)
print('검증:','\n', ar.dot(ar_a).round(1))

행렬: 
 [[4 5 1 2 4]
 [1 1 2 5 5]
 [2 3 5 3 5]
 [4 5 3 5 3]
 [5 2 2 1 2]]
역행렬: 
 [[-0.039801  0.039801 -0.11194  -0.012438  0.278607]
 [ 0.174129 -0.174129  0.052239  0.116915 -0.218905]
 [-0.195688 -0.137645  0.241294  0.063847  0.036484]
 [-0.139303  0.139303 -0.141791  0.206468 -0.024876]
 [ 0.190713  0.14262   0.057214 -0.252902 -0.001658]]
검증: 
 [[ 1. -0.  0. -0.  0.]
 [ 0.  1. -0. -0.  0.]
 [ 0. -0.  1. -0.  0.]
 [ 0.  0. -0.  1.  0.]
 [ 0.  0. -0.  0.  1.]]


### Q7. 표준정규분포 난수로 10행 5열 2차원 배열 ar을 생성하고 ar_test 이름으로 저장한 후 다시 불러내서 출력하세요.

In [71]:
np.random.seed(0)
ar = np.random.randn(10,5)
np.save('ar_test',ar)
np.load('ar_test.npy')

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785, -0.21274028]])

### Q8. df = sns.load_dataset('titanic')로 불러와서 다음 작업을 수행한 후 출력하세요.
- 전체 칼럼중 'survived','who','adult_male','deck','embark_town','alive','alone' 칼럼을 제외한
df_x 데이터프레임을 생성한 후 dataset/df_x.pkl로 저장한다.
- df_x.pkl을 데이터프레임 df_x 이름으로 불러온 후 앞 5개 행을 출력한다. 

In [76]:
import seaborn as sns
df = sns.load_dataset('titanic')
df_x = df[['pclass','sex','age','sibsp','parch','fare','class','embarked']]

df_x = df_x.to_pickle('/Users/joy/cakd3/dataset/df_x.pkl')
df_x = pd.read_pickle('/Users/joy/cakd3/dataset/df_x.pkl')
df_x.head()

pclass     sex   age  sibsp  parch     fare  class embarked
0       3    male  22.0      1      0   7.2500  Third        S
1       1  female  38.0      1      0  71.2833  First        C
2       3  female  26.0      0      0   7.9250  Third        S
3       1  female  35.0      1      0  53.1000  First        S
4       3    male  35.0      0      0   8.0500  Third        S

### Q9. Q.8의 df_x에서 각 칼럼별 null 개수를 구하세요.

In [77]:
df_x.isnull().sum()

pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
class         0
embarked      2
dtype: int64

### Q10. df_x의 전체 null 갯수를 계산하세요.

In [78]:
df_x.isnull().sum().sum()

179

### Q11. tdf에서 fare를 3개 카테고리로 구분하는 새로운 칼럼 'fare_age'를 생성하여 출력하세요. 단, 카테고리 구분을 수행하는 사용자 함수를 만들고 그 함수를 fare 칼럼에 매핑하여 결과를 tdf에 저장하고 출력하세요.

[카테고리]  
fare <= 7.9: cat = 'T'  
fare <= 31: cat = 'S'  
fare > 31 : cat = 'F'

In [248]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class','fare']]
tdf.head()

def fare_cat(fare):
    cat = ''
    if fare <= 7.9: 
        cat = 'T'
    elif fare <= 31: 
        cat = 'S'
    elif fare > 31 : 
        cat = 'F'
    return cat

fare_cat = tdf.age.transform(fare_cat)
# df['fare']=df.fare.apply(lambda x : fare_cat(x))
tdf['fare_cat'] = fare_cat
tdf

/Applications/anaconda3/envs/cakd3/lib/python3.9/site-packages/pandas/core/frame.py:3607: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._set_item(key, value)


survived     sex   age   class     fare fare_cat
0           0    male  22.0   Third   7.2500        S
1           1  female  38.0   First  71.2833        F
2           1  female  26.0   Third   7.9250        S
3           1  female  35.0   First  53.1000        F
4           0    male  35.0   Third   8.0500        F
..        ...     ...   ...     ...      ...      ...
886         0    male  27.0  Second  13.0000        S
887         1  female  19.0   First  30.0000        S
888         0  female   NaN   Third  23.4500         
889         1    male  26.0   First  30.0000        S
890         0    male  32.0   Third   7.7500        F

[891 rows x 6 columns]

### Q12.  df의 gender, code 칼럼을 '_'으로 연결한 'gc'칼럼을 추가한 후 출력하세요. 단, 타입변환을 유의해서 수행하세요.
연결 예시 : m_10

In [106]:
df = pd.DataFrame({'gender' : ['m', 'f', 'f'],\
                   'code' : [10, 20, 30]})
df
df['code'] = df.code.apply(lambda x : str(x))
df['gc'] = df[['gender','code']].agg('_'.join, axis=1)
df

gender code    gc
0      m   10  m_10
1      f   20  f_20
2      f   30  f_30

### Q13. join() 메소드는 두 데이터프레임의 행 인덱스를 기준으로 결합한다. 2개의 주식데이터를 가져와서 join() 메소드로 아래와 같이 결합한 후 다음 사항을 수행하세요.
- 데이터 셋
1. 'dataset/stock price.xlsx'
2. 'dataset/stock valuation.xlsx'
- df1과 df2의 합집합이 출력되도록 결합하여 df4에 저장하고 출력
- df4에서 중복된 칼럼 name 을 삭제한 후 블린 인덱싱을 이용하여 eps가 10000 보다 크고 stock_name이 이마트인 데이터를 선택하여 데이터프레임을 생성하고 df5 이름으로 저장 및 출력하세요.(단, '<' 와 '==' 를 반드시 사용해야 함)

In [250]:
df1 = pd.read_excel('/Users/joy/cakd3/시험문제/stock_price.xlsx', index_col='id')
df2 = pd.read_excel('/Users/joy/cakd3/시험문제/stock_valuation.xlsx', index_col='id')

df4 = df1.join(df2, how='outer')
print(df4)
df4.drop('name', axis=1, inplace=True)
df5 = df4[(df4['eps']>10000)&(df4['stock_name']=='이마트')]

df5

       stock_name          value     price       name           eps       bps  \
id                                                                              
128940       한미약품   59385.666667  421000.0        NaN           NaN       NaN   
130960     CJ E&M   58540.666667   98900.0     CJ E&M   6301.333333   54068.0   
136480        NaN            NaN       NaN         하림    274.166667    3551.0   
138040        NaN            NaN       NaN    메리츠금융지주   2122.333333   14894.0   
138250      엔에스쇼핑   14558.666667   13200.0        NaN           NaN       NaN   
139480        이마트  239230.833333  254500.0        이마트  18268.166667  295780.0   
142280     녹십자엠에스     468.833333   10200.0        NaN           NaN       NaN   
145990        삼양사   82750.000000   82000.0        삼양사   5741.000000  108090.0   
161390        NaN            NaN       NaN      한국타이어   5648.500000   51341.0   
181710        NaN            NaN       NaN  NHN엔터테인먼트   2110.166667   78434.0   
185750        종근당   40293.66

stock_name          value     price           eps       bps        per  \
id                                                                              
139480        이마트  239230.833333  254500.0  18268.166667  295780.0  13.931338   

             pbr  
id                
139480  0.860437

### Q14.  df의 score1 과 score2 컬럼을 합한 숫자로 구성된 새로운 컬럼 score3을 생성 후 df를 출력하세요.

In [129]:
import numpy as np
import pandas as pd
np.random.seed(0)
df = pd.DataFrame(np.random.randint(123456789,123456791,size=(2,2)),columns= ['score1','score2'])
df['score1'] = '123,234,567'
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   score1  2 non-null      object
 1   score2  2 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [141]:
df['score1'] = df['score1'].apply(lambda x: x.replace(',',''))

df['score1'] = df.score1.apply(lambda x: int(x))

df['score3'] = df['score1'] + df['score2']

df

score1     score2     score3
0  123234567  123456790  246691357
1  123234567  123456789  246691356

### Q15. auto_df의 horsepower 컬럼에서 숫자가 아닌 원소들을 0으로 대체한 후에 전체 평균을 구한 후 소숫점 2째 자리까지만 출력하세요.

In [253]:
import pandas as pd
auto_df = pd.read_csv('/Users/joy/cakd3/dataset/auto-mpg.csv')
auto_df.head()

print(auto_df.horsepower.unique())

auto_df['horsepower'] = auto_df.horsepower.apply(lambda x : x.replace('?','0'))
auto_df['horsepower'] = auto_df.horsepower.apply(lambda x : float(x))

auto_df.horsepower.unique()
auto_df.horsepower.mean().round(2)

['130' '165' '150' '140' '198' '220' '215' '225' '190' '170' '160' '95'
 '97' '85' '88' '46' '87' '90' '113' '200' '210' '193' '?' '100' '105'
 '175' '153' '180' '110' '72' '86' '70' '76' '65' '69' '60' '80' '54'
 '208' '155' '112' '92' '145' '137' '158' '167' '94' '107' '230' '49' '75'
 '91' '122' '67' '83' '78' '52' '61' '93' '148' '129' '96' '71' '98' '115'
 '53' '81' '79' '120' '152' '102' '108' '68' '58' '149' '89' '63' '48'
 '66' '139' '103' '125' '133' '138' '135' '142' '77' '62' '132' '84' '64'
 '74' '116' '82']


102.89

### Q16. './dataset/stock-data.csv'를 데이터프레임으로 불러와서 Date 컬럼 판다스 Timestamp로 변환한 후 인덱스로 셋팅하고 Date 컬럼은 삭제한 후 처음 5개 행만 출력하세요.

In [255]:
from datetime import datetime
import time
df = pd.read_csv('/Users/joy/cakd3/dataset/stock-data.csv')
df.info()

# str -> timestamp
# time = time.mktime(datetime.strftime(s).timetuple())
# df['Date'] = df.Date.apply(lambda x : time.mktime(datetime.strftime(x).timetuple()))

df['new_Date'] = pd.to_datetime(df['Date'])
df.drop('Date',axis=1, inplace=True)
df.set_index('new_Date').head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Date    20 non-null     object
 1   Close   20 non-null     int64 
 2   Start   20 non-null     int64 
 3   High    20 non-null     int64 
 4   Low     20 non-null     int64 
 5   Volume  20 non-null     int64 
dtypes: int64(5), object(1)
memory usage: 1.1+ KB


Close  Start   High    Low  Volume
new_Date                                      
2018-07-02  10100  10850  10900  10000  137977
2018-06-29  10700  10550  10900   9990  170253
2018-06-28  10400  10900  10950  10150  155769
2018-06-27  10900  10800  11050  10500  133548
2018-06-26  10800  10900  11000  10700   63039

### Q17. titanic 데이터셋에서 아래 5개 열을 선택하고 sex 컬럼을 기준으로 그룹화를 수행한 후 다음 사항을 출력하세요.
5개 열 : ['age','sex', 'class', 'fare', 'survived']  
- 그룹별 평균 출력
- 그룹별 최대값 출력

In [265]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [264]:
titanic = titanic[['age','sex','class','fare','survived']]
titanic = titanic.groupby('sex')
print(titanic.mean(), '\n')
print(titanic.max())

              age       fare  survived
sex                                   
female  27.915709  44.479818  0.742038
male    30.726645  25.523893  0.188908 

         age      fare  survived
sex                             
female  63.0  512.3292         1
male    80.0  512.3292         1


<ipython-input-264-d95ee486640c>:4: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  print(titanic.max())


### Q18. titanic 데이터셋에서 class, age, fare, survived 4개 컬럼만 선택하여 df를 생성한 후 class 컬럼의  'First'그룹만을 선택해서 group1 이름으로 저장하고 통계요약표를 출력하세요.

In [262]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset('titanic')

df = titanic[['class','age','fare','survived']]
grouped = df.groupby(['class'])
group1 = grouped.get_group('First')
group1.describe()

age        fare    survived
count  186.000000  216.000000  216.000000
mean    38.233441   84.154687    0.629630
std     14.802856   78.380373    0.484026
min      0.920000    0.000000    0.000000
25%     27.000000   30.923950    0.000000
50%     37.000000   60.287500    1.000000
75%     49.000000   93.500000    1.000000
max     80.000000  512.329200    1.000000

### Q19. titanic 데이터셋에서 class 열, sex열 기준으로 그룹화한 후 그룹별 최대값과 최소값을 구하세요.

In [275]:
titanic = sns.load_dataset('titanic')
df = titanic[['class','sex', 'age', 'fare', 'survived']]
df

class     sex   age     fare  survived
0     Third    male  22.0   7.2500         0
1     First  female  38.0  71.2833         1
2     Third  female  26.0   7.9250         1
3     First  female  35.0  53.1000         1
4     Third    male  35.0   8.0500         0
..      ...     ...   ...      ...       ...
886  Second    male  27.0  13.0000         0
887   First  female  19.0  30.0000         1
888   Third  female   NaN  23.4500         0
889   First    male  26.0  30.0000         1
890   Third    male  32.0   7.7500         0

[891 rows x 5 columns]

In [278]:
grouped1 = df.groupby('class')
print(grouped1.agg(['max','min']))

print('\n','--------','\n')

grouped2 = df.groupby('sex')
print(grouped2.agg(['max','min']))


# grouped3 = df.groupby(['class','sex'])
# print(grouped3.agg(['max','min']))

         sex           age            fare      survived    
         max     min   max   min       max  min      max min
class                                                       
First   male  female  80.0  0.92  512.3292  0.0        1   0
Second  male  female  70.0  0.67   73.5000  0.0        1   0
Third   male  female  74.0  0.42   69.5500  0.0        1   0

 -------- 

         age            fare       survived    
         max   min       max   min      max min
sex                                            
female  63.0  0.75  512.3292  6.75        1   0
male    80.0  0.42  512.3292  0.00        1   0
                age            fare          survived    
                max   min       max      min      max min
class  sex                                               
First  female  63.0  2.00  512.3292  25.9292        1   0
       male    80.0  0.92  512.3292   0.0000        1   0
Second female  57.0  2.00   65.0000  10.5000        1   0
       male    70.0  0.67   73.50

### Q20.  titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'deck' 컬럼만을 선택하여 df1 이름으로 저장 후 출력하세요. 
2. df1에서 null값이 50% 이상인 칼럼은 삭제한 후 df2를 생성하고 df2에 null이 있는 컬럼은 적절한 값으로 대체한 후 df2의 null값의 갯수가 0인지 확인하세요.
3. df2에서 문자로 되어있는 칼럼들을 원핫 인코딩 수행하여 숫자로 변환 후 처음 5개 행을 출력하세요

In [268]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [269]:
# 1. df에서 'survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'deck' 컬럼만을 
# 선택하여 df1 이름으로 저장 후 출력하세요.

df1 = df[['survived','pclass','sex','age','sibsp','parch','fare','embarked','deck']]
df1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [272]:
# 2. df1에서 null값이 50% 이상인 칼럼은 삭제한 후 df2를 생성하고 df2에 null이 있는 
# 컬럼은 적절한 값으로 대체한 후 df2의 null값의 갯수가 0인지 확인하세요.
df1.info()
df2 = df1.drop('deck',axis=1)
df2['age'] = df2.age.fillna(df2['age'].mean())
df2['embarked'] = df2.embarked.fillna('A')

df2.isnull().sum().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   survived  891 non-null    int64   
 1   pclass    891 non-null    int64   
 2   sex       891 non-null    object  
 3   age       714 non-null    float64 
 4   sibsp     891 non-null    int64   
 5   parch     891 non-null    int64   
 6   fare      891 non-null    float64 
 7   embarked  889 non-null    object  
 8   deck      203 non-null    category
dtypes: category(1), float64(2), int64(4), object(2)
memory usage: 57.0+ KB


0

In [279]:
# 3. df2에서 문자로 되어있는 칼럼들을 원핫 인코딩 수행하여 숫자로 변환 후 처음 5개 행을 출력하세요. ->sex, embarked
# pd.get_dummies(df2).head()
# pd.get_dummies(df2[['sex','embarked']]).head()

sex_female  sex_male  embarked_A  embarked_C  embarked_Q  embarked_S
0           0         1           0           0           0           1
1           1         0           0           1           0           0
2           1         0           0           0           0           1
3           1         0           0           0           0           1
4           0         1           0           0           0           1