## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

### 교과목명 : 통계 및 ml 기초
- 평가일 : 21.8.20
- 성명 : 조경림
- 점수 :

Q1. 다음 괄호안에 들어갈 적합한 단어를 기술하세요.(20점)

확률 변수(random variable)은 확률 실험의 결과에 대한 숫자적 표현입니다. 가령 동전을 던진다고 했을 때 앞면을 1, 뒷면을 0이라고 표현한다고 하면 이는 실험 결과의 숫자적 표현이고 확률 변수입니다. 확률 변수는 그것이 취할 수 있는 값들이 한 개, 두개와 같이 셀 수 있으면 (이산) 확률 변수(discrete random variable), 셀 수 없을 경우 (연속) 확률 변수(continuous random variable)이라 부릅니다. 동전의 경우 나올 수 있는 경우의 수가 앞 면 또는 뒷 면으로 두 가지니까니 (이산) 확률 변수입니다. 그러나 같은 반 아이들의 키 처럼 확률 변수가 가질 수 있는 가지 수가 무한한 경우 (연속) 확률 변수에 속하게 됩니다.

확률변수가 취할 수 있는 값들에는 확률이 대응되어 있고, 이를 (확률분포)라고 합니다. 즉 확률 변수들이 어떠한 형태로 놓여있을까, 어떻게 분포해 있을까를 나타내주는 함수입니다. ( 확률분포 ) 역시 확률 변수가 이산형 확률 변수이냐, 연속형 확률 변수이냐에 따라서 (이산확률분포 ), ( 연속확률분포 )로 나뉩니다.

( 이항분포 )란 고정된 지역, 시간 또는 부피 등에서 관심 있는 사건의 관찰 수 또는 발생 횟수 X를 표현하는데 사용되는 분포입니다. 예를 들면 하루 동안 서버에 접속한 사용자 수, 어느 주말 일요일에 발생한 교통사고 사망자 수 등이 있습니다. 

평균을 중심으로 좌우가 대칭인 종 모양을 그리는 ( 정규분포 )는 표준 편차가 높을 수록 그래프는 완만한 곡선 형태를 띄게 됩니다. 

현실 세계의 많은 데이터들은 정규분포를 따르고 있습니다. 하지만 각 집단의 평균과 표준 편차가 모두 다르기 때문에 데이터들을 서로 비교하기가 어렵습니다. 예를 들어 A반의 수학 점수가 평균은 70점이고 표준 편자는 30점입니다. 반면 B반은 평균 65점에 표준 편차가 10점이라면 두 반 중 어느 반이 더 수학  점수가 높다고 할 수 있을까요? 이러한 비교를 위해서 전체 데이터를 평균으로 빼주고, 표준 편차로 나누어 주는 표준화(standardizing) 작업을 거치게 됩니다. 그 결과 두 집단의 수학 점수는 동일하게 (t 분포 )를 따르게 되며 평균이 0이고 분산이 1인 정규 분포가 됩니다. 수식으로는 Z = (X - mu) / sigma로  표현할 수 있습니다. 표준화를 거친 개별 데이터를 우리는 ( 표준화 데이터 )라고 부릅니다.

( t분포 )는 정규 분포인 모집단의 모평균을 표본 평균을 통해서 추측할 때 사용되는 분포입니다. 정규 분포와 유사한 형태를 갖지만 양 끝단에 데이터가 더 많이 분포하는 형태를 띕니다. 모집단에서 표본을 추출할 경우 표준 편차가 더 커질 것이라는 것을 예상할 수 있습니다. 이 때문에 곡선의 모양이 더 완만해 지는 것을 ( t분포 )로 설명한다고 이해하면 좋을 것 같습니다.

정규 분포의 경우 그래프의 형태를 표준 편차와 평균이 결정하였습니다. t-분포는 이 둘에 더해 수식 상에서 (n-1)에 해당하는 (자유도 )가 그래프의 형태에 영향을 줍니다. ( 자유도 )의 정의는 말 그래도 자유스러운 정도로 특정 분포에서 그래프의 모양을 결정하는 모수입니다. 대표적으로 t 분포와 카이제곱 분포가 (자유도 )를 모수로 갖습니다.

(F분포)는 f 검정이나 분산 분석에서 많이 활용된다고 합니다. (F분포)는 두 모분산의 비율에 대한 추정을 할 떄 사용됩니다.

(카이제곱검정)은 관찰된 빈도가 기대 빈도와 통계적으로 다른지를 판단하는 검증방법으로 사용한다.

모집단의 표본에서 얻은 통계량을 통해 모집단의 통계적 특성을 추측할 수 있습니다. 이러한 과정을 논리적으로 전개하기 위해서 필요한 것이 가설과 검정입니다. 가설(hypothesis)란 확률 분포에 대한 어떠한 주장이며 이를 증명하는 행위를 검정(testing)이라 합니다. 특히 확률 분포의 모수 값에 대한 가설을 검정하는 것을 ( 모수검정 )이라 부릅니다.

(귀무가설)은 처음부터 버릴 것을 예상하는 가설입니다. 기본적으로 참으로 추정되며 이를 거부하기 위해서는 증거가 반드시 필요합니다. 예를들어 형사가 용의자를 잡았을 경우에도 무죄 추정의 원칙에 따라서 '이 용의자는 무죄일 것이다' 라는 가설을 먼저 세우게 됩니다.(귀무가설)을 세울 때에는 특별한 증거가 없다면 참으로 여겨지는 가설을 (귀무가설 )로 세우게 됩니다.

( 대립가설 )란 귀무 가설이 맞는데도 이를 잘못 기각하여 발생하는 오류입니다.  용의자가 무죄가 맞지만 잘못하여 유죄 판결을 내리는 것과 같습니다. (1형 오류)란 대립 가설이 사실임에도 불구하고 귀무가설을 기각하지 못하는 오류를 말합니다. 용의자가 범인이 맞지만 무죄가 아니라는 것을 입증해내지 못하는 것을 말합니다.

( p-value )란 귀무 가설이 맞다고 가정할 때 얻은 결과보다 극단적인 결과가 관측될 확률입니다.

( 임계값 )은 귀무가설을 기각하는 기준이 되는 값이다.

통계모델에 사용하는 파라미터를 계수라고 하는 반면 머신러닝에서는 (  20  )라고 표현한다.

Q2. 다음의 확률밀도함수를 그래프로 표현하고 모집단 분포와 비교한 후 t분포의 특징을 기술하세요.(5)
- 표준정규분포
- 표준정규분포인 모집단에서 샘플 10개를 추출한 표본의 t분포
- 평균 0, 표준편차 2인 정규분포
- 평균 0, 표준편차 2인 정규분포인 모집단에서 샘플 5개를 추출한 표본의 t분포

Q3. t검정과 관련 다음 사항에 대하여 기술하세요.(5)
- t검정을 사용하는 경우
- t검정에 사용하는 t-value 산출 방법 
- t-value와 z score 간의 의미상 차이

A3. 
1. t-검정을 사용하는 경우는 두 집단간의 차이 여부를 분석할 때로, 그 종류로는 일원표본/대응표본/독립표본에 대한 분석이 있다.
2.  t-value 산출법 : 
1) 일원표본, 대응표본 : (표본평균-모평균)/(시그마/모수를 루트한 값)
2) 독립표본 :(표본1평균-표본2평균)/(표본1의 표본수 분의 분산 + 표본2의 표본수 분의 분산을 루트한 값)
3. t-value는 가정된 값에서 표준 오류에 대한 모수의 추정값 이탈의 비율로 얼마나 정확한지를 나타냄
z score는 정규분포 상에서 어느정도위치를 차지하고 있는지 알려주는 값이다. 

Q4. 남성 키의 평균 170 표준편차는 5인 모집단 생성(size=2000) 후 그 중 10개를 출력하세요.

In [8]:
import numpy as np
from scipy import stats
data = np.random.normal(170,5,size=2000)
data[:10]

array([172.1777308 , 167.00387861, 170.16544876, 165.7291937 ,
       166.40029734, 165.53212799, 169.21988055, 175.24546594,
       185.85487387, 170.94749819])

Q5. Q4에서 생성된 모집단에서 20개의 샘플을 추출한 후 아래 사항을 수행하세요. 단 모집단의 분산은 알 수가 없다는 것을 가정한다.
- 추출한 샘플1, 샘플2로 부터 남성의 평균 키가 170이다라는 가설을 세우고 검정
- 샘플2를 기준으로 표준오차를 구하세요
- 샘플2를 기준으로 95% 신뢰수준으로 신뢰구간을 구하세요

In [9]:
# sample 추출
np.random.seed(0)
sample1 = np.random.choice(data,20,replace=False)
sample2 = data[:20]
sample1

array([173.48219337, 170.91714323, 169.26181293, 172.00265342,
       165.16534456, 167.01664572, 169.69252618, 169.63880621,
       169.23602768, 170.49188953, 167.70186779, 179.79781003,
       167.19210625, 171.12920239, 172.98606252, 175.89709991,
       164.60328417, 170.80553161, 174.71157154, 175.82075883])

In [18]:
# 가설 세우기 : '추출한 샘플1, 샘플2로 부터 남성의 평균 키가 170이다라'
print(sample1.mean())
print(sample2.mean())

170.8775168937163
170.04839089932824


In [19]:
# 표준오차 및 신뢰구간
error = np.std(data, ddof=1)/np.sqrt(len(data))
print('표준오차 : ', error)
a = stats.t.interval(0.95, len(data)-1, loc=np.mean(data), scale=stats.sem(data))
print('신뢰구간 : ', a)

표준오차 :  0.10764441743978918
신뢰구간 :  (169.6756363458106, 170.09785035008153)


Q6. 어느 자동차 임대 회사에서 3가지 종류의 휘발유를 비교하는데 관심이 있다. 각 종류의 휘발유에 대하여 4번의 주행을 하여 반응변수로서 각 주행에 대한 리터당 주행거리를 구하였다.(qsample.csv) 다음 사항을 고려하여 휘발유간의 주행거리 차이가 유의미한지를 분산분석을 사용하여 검정하세요.
- 각 휘발유의 4개의 실험에서의 주행거리가 다름 = 실험오차(군내변동)
- 휘발유 종류에 따라 각 평균 주행거리가 서로 다름(군간변동)

In [20]:
import pandas as pd
df = pd.read_csv('/Users/joy/Documents/GitHub/0Oong/시험문제/qsample.csv')
df

product  distance
0      제품1      15.2
1      제품1      16.1
2      제품1      16.8
3      제품1      15.9
4      제품2      18.5
5      제품2      17.5
6      제품2      18.2
7      제품2      17.8
8      제품3      19.6
9      제품3      19.3
10     제품3      18.4
11     제품3      18.7

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   product   12 non-null     object 
 1   distance  12 non-null     float64
dtypes: float64(1), object(1)
memory usage: 320.0+ bytes


In [27]:
df['Product'] = df['product']
df = df.drop('product', axis=1)
df

distance Product
0       15.2     제품1
1       16.1     제품1
2       16.8     제품1
3       15.9     제품1
4       18.5     제품2
5       17.5     제품2
6       18.2     제품2
7       17.8     제품2
8       19.6     제품3
9       19.3     제품3
10      18.4     제품3
11      18.7     제품3

In [31]:
import statsmodels.formula.api as smf
import statsmodels.api as sm
anova_model = smf.ols('distance~Product', data=df).fit() #군간, 모델의 자유도
sm.stats.anova_lm(anova_model, type=2)

# 결론 : 군간변동의 자유도 2, 군내변동의 자유도9, F비가 0.05보다 작으므로 변수들끼리 관련이 있다고 할 수 있다. 
# 따라서 휘발유간 주행거리 차이가 유의미하다. 

df     sum_sq   mean_sq          F    PR(>F)
Product   2.0  18.666667  9.333333  30.215827  0.000102
Residual  9.0   2.780000  0.308889        NaN       NaN

Q7. 비만과 당뇨의 상관관계를 분석하기 위하여 조사한 결과로 qsample2 데이터를 작성하였다. 비만과 당뇨가 서로 독립적인지를 판단하기 위한 카이스퀘어 검정을 수행 하세요.

In [49]:
obs = pd.read_csv('/Users/joy/Documents/GitHub/0Oong/시험문제/qsample2.csv')
print(obs.info())
obs

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   당뇨      2 non-null      int64 
 1   정상      2 non-null      int64 
 2   index   2 non-null      object
dtypes: int64(2), object(1)
memory usage: 176.0+ bytes
None


당뇨  정상 index
0  10  10  비만체중
1  15  65  정상체중

In [52]:
obs = obs.groupby('index').sum()
obs

당뇨  정상
index        
비만체중   10  10
정상체중   15  65

In [53]:
stats.chi2_contingency(obs, correction=False)

(8.333333333333334,
 0.003892417122778637,
 1,
 array([[ 5., 15.],
        [20., 60.]]))

기대도수는 모두 5보다 크므로 유의미하다. 하지만 p값이 0.05보다 작기 때문에 '당뇨와 비만은 독립적이다'라는 귀무가설은 기각되고 당뇨와 비만은 상관관계가 있다는 대립가설이 채택될 수 있다. 

Q8.'7_1_beer.csv' 데이터 셋에서 온도의 변화에 따른 맥주 매상 예측 모델을 statsmodel 라이브러리를 활용하여 수행 후 summary() 결과를 해석하세요. 

In [54]:
beer = pd.read_csv('/Users/joy/Documents/GitHub/0Oong/수업내용/dataset/7_1_beer.csv')
beer.head()

beer  temperature
0  45.3         20.5
1  59.3         25.0
2  40.4         10.0
3  38.0         26.9
4  37.0         15.8

In [62]:
beer_lm=smf.ols("beer~temperature", data = beer).fit()
beer_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   beer   R-squared:                       0.504
Model:                            OLS   Adj. R-squared:                  0.486
Method:                 Least Squares   F-statistic:                     28.45
Date:                Fri, 20 Aug 2021   Prob (F-statistic):           1.11e-05
Time:                        15:38:49   Log-Likelihood:                -102.45
No. Observations:                  30   AIC:                             208.9
Df Residuals:                      28   BIC:                             211.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      34.6102      3.235     10.699      0.000      27.984      41.237
temperature     0.7654      0.144      5.334      0.000       0.471       1.059
==============================================================================
Omnibus:                        0.587   Durbin-Watson:                   1.960
Prob(Omnibus):                  0.746   Jarque-Bera (JB):                0.290
Skew:                          -0.240   Prob(JB):                        0.865
Kurtosis:                       2.951   Cond. No.                         52.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

Df Model은 샘플수(30) - 파라미터수(1)- Df Model(사용된 독립변수)로 28이며 
R2는 1에 가까울수록 회귀식이 타당한 것인데 0.5정도로 애매하다. 조정된 R2도 0.48로 애매하다. F비를 봤을 때는 0.05보다 작기때문에 변수끼리 관련이 높아 유의미하다고 볼 수 있으다. 
절편은 약 34, 계수(temperature)의 값은 0.7이며 omnibus의 경우 값이 클수록 잔차가 정규분포를 따른다는 뜻인데 0.58로 애매하다. 하지만 전반적으로 유의미하다고 할 수 있다. 

Q9.iris 데이터셋으로 분류 분석을 수행하고 평가하세요. 

In [65]:
from sklearn.datasets import load_iris

In [66]:
iris = load_iris()
iris_label=iris.target #종속
iris_data=iris.data #독립
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris_label
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [67]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   label              150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [69]:
# 데이터 분리
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(iris_data,
                                                iris_label,
                                                test_size=0.3,
                                                random_state=10)

In [72]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [73]:
# 예측 수행
pred = dt_clf.predict(X_test)

In [74]:
from sklearn.metrics import accuracy_score
print("예측 정확도: {0:.4f}".format(accuracy_score(y_test,pred)))

예측 정확도: 0.9778


Q10. 'auto-mpg' 데이터셋에서 horsepower에 따른 mpg를 예측하는 선형회귀 모델을 생성한 후 정확도 평가를 수행하세요.(단, 종속변수의 정규성을 개선해야 함)

In [91]:
df = pd.read_excel("/Users/joy/Documents/GitHub/0Oong/수업내용/dataset/auto-mpg.xlsx")
ndf=df[['mpg','cylinders','horsepower','weight']]
ndf.head()

mpg  cylinders horsepower  weight
0  18.0          8        130    3504
1  15.0          8        165    3693
2  18.0          8        150    3436
3  16.0          8        150    3433
4  17.0          8        140    3449

In [92]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   mpg         398 non-null    float64
 1   cylinders   398 non-null    int64  
 2   horsepower  398 non-null    object 
 3   weight      398 non-null    int64  
dtypes: float64(1), int64(2), object(1)
memory usage: 12.6+ KB


### horsepower 결측치 제거

In [93]:
ndf.horsepower.unique()

array([130, 165, 150, 140, 198, 220, 215, 225, 190, 170, 160, 95, 97, 85,
       88, 46, 87, 90, 113, 200, 210, 193, '?', 100, 105, 175, 153, 180,
       110, 72, 86, 70, 76, 65, 69, 60, 80, 54, 208, 155, 112, 92, 145,
       137, 158, 167, 94, 107, 230, 49, 75, 91, 122, 67, 83, 78, 52, 61,
       93, 148, 129, 96, 71, 98, 115, 53, 81, 79, 120, 152, 102, 108, 68,
       58, 149, 89, 63, 48, 66, 139, 103, 125, 133, 138, 135, 142, 77, 62,
       132, 84, 64, 74, 116, 82], dtype=object)

In [95]:
ndf['horsepower'].replace('?',np.nan, inplace=True)


/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4509: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(


In [100]:
ndf['horsepower'].fillna(method='ffill', inplace=True)

/Applications/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4463: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(


In [101]:
ndf.horsepower.unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
       100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,  65.,
        69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137., 158.,
       167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,  78.,
        52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,  81.,
        79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,  48.,
        66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62., 132.,
        84.,  64.,  74., 116.,  82.])

### Scaler

In [106]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
ndf_ms = scaler.fit_transform(ndf)
ndf_ms_df = pd.DataFrame(data=ndf_ms,columns=ndf.columns)
ndf_ms_df.head()

mpg  cylinders  horsepower    weight
0  0.239362        1.0    0.456522  0.536150
1  0.159574        1.0    0.646739  0.589736
2  0.239362        1.0    0.565217  0.516870
3  0.186170        1.0    0.565217  0.516019
4  0.212766        1.0    0.510870  0.520556

### 선형회귀모델

In [107]:
lm_model = smf.ols(formula="horsepower~mpg", data=ndf).fit()

In [108]:
lm_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             horsepower   R-squared:                       0.605
Model:                            OLS   Adj. R-squared:                  0.604
Method:                 Least Squares   F-statistic:                     606.0
Date:                Fri, 20 Aug 2021   Prob (F-statistic):           7.63e-82
Time:                        16:20:18   Log-Likelihood:                -1830.3
No. Observations:                 398   AIC:                             3665.
Df Residuals:                     396   BIC:                             3673.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    193.7762      3.835     50.529      0.000     186.237     201.316
mpg           -3.8103      0.155    -24.617      0.000      -4.115      -3.506
==============================================================================
Omnibus:                       48.086   Durbin-Watson:                   1.059
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               75.280
Skew:                           0.770   Prob(JB):                     4.50e-17
Kurtosis:                       4.472   Cond. No.                         78.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

summary를 본 결과 R2가 0.6, F비가 0.05보다 작으므로 유의미하다고 볼 수 있다. 따라서 horsepower와 mpg간의 상관관계가 있다고 할 수 있다.